model_name: meta-llama/Llama-3.2-1B # "meta-llama/Llama-3.2-1B" or "distilbert/distilbert-base-uncased"
pretrained_model_exists: True # True or False
device: cuda #cuda:0 or cpu
data_path: data/out.jsonl # Path to the data file
output_dir: output # Path to the output directory
random_seed: 42 # Random seed for reproducibility

learning_rate: 1e-4 # Learning rate for the optimizer
batch_size: 4 # Batch size for training
epochs: 1 # Number of epochs to train the model